### ISSUE TITLE
Unable to issue / renew cert anymore

### ISSUE THREAD

**Issue by Mhisani** [infinityofspace/certbot_dns_porkbun#3]
I'm hoping this isn't a "me" problem but no matter what I do I am unable to get wildcard to work via porkbun dns / certbot.

It did work but not I get the error:

2021-05-23 14:24:23,496:DEBUG:urllib3.connectionpool:https://porkbun.com:443 "POST /api/json/v3/dns/create/co.uk HTTP/1.1" 400 None
2021-05-23 14:24:23,499:DEBUG:certbot._internal.error_handler:Encountered exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/certbot_dns_porkbun/cert/client.py", line 87, in _perform
    self.record_ids[validation] = self._get_porkbun_client().dns_create(root_domain, "TXT", validation,
  File "/usr/local/lib/python3.9/dist-packages/pkb_client/client.py", line 115, in dns_create
    raise Exception("ERROR: DNS create api call was not successfully\n"
Exception: ERROR: DNS create api call was not successfully
Status code: 400
Message: Invalid domain.

I have checked and checked but I can not work out what's wrong.

**Comment by infinityofspace** [comment]
The error message indicates that you are trying to create a DNS record for a domain that does not belong to you or does not exists:

> Exception: ERROR: DNS create api call was not successfully
Status code: 400
Message: Invalid domain.

The error message also states that you are trying to generate a certificate for the domain `co.uk`:

> /api/json/v3/dns/create/**co.uk**

I assume that this is not the actual domain but the top and second level domain of your actual domain like `example.co.uk`.

Could you please provide the certbot command, certbot/certbot_dns_porkbun versions and especially the domain you used there in an anonymized form:
- replace any secrets with placeholder like `--dns-porkbun-key <my-secret-token>`
- replace parts of the domain but keep the structure for subdomains, second level and top level domains
  examples:
  -  `mhisani.co.uk` -> `example.sld.tld`
  - `*.mhisani.co.uk` -> `*.example.sld.tld`
  - `example.mhisani.co.uk` -> `example.mydomain.sld.tld`
  -  `mhisani.com` -> `example.tld`

**Comment by Mhisani** [comment]
Thankyou very much for your fast reply and time! As requested:


> certbot certonly   --non-interactive   --agree-tos   --email someguy@someemail.local  --preferred-challenges dns   --authenticator dns-porkbun   --dns-porkbun-key <secret pk1>  --dns-porkbun-secret <secret sk1> --dns-porkbun-propagation-seconds 60   -d *.someexampledomain.co.uk



Encountered exception during recovery: KeyError: 'SomeLongKeyHere'
ERROR: DNS create api call was not successfully
Status code: 400
Message: Invalid domain.

**Comment by infinityofspace** [comment]
Thanks for the further details.
It seems the correct processing of arbitrary number of subdomains which are part of the top level domain (`example.abc.com`, `example.xyz.abc.com`) does not work and result in a wrong domain name. I have found the cause and will fix it as soon as possible in a hotfix release.
