### ISSUE TITLE
Unable to renew certificate

### ISSUE THREAD

**Issue by 3nt3** [infinityofspace/certbot_dns_porkbun#55]
**Describe the bug**
API calls fail with status 400 and message `Invalid domain`

**To Reproduce**
```
certbot certonly -d '*.domain, domain'
```

**Expected behavior**
Complete DNS challenge and renew certificates. 

**Versions (please complete the following version information):**
 - certbot: 1.29.0
 - certbot_dns_porkbun: 0.6

**Error message**
```
Encountered exception during recovery: KeyError: 'loooong key'
ERROR: DNS create api call was not successfully
Status code: 400
Message: Invalid domain.
```

**Comment by infinityofspace** [comment]
Thanks for your report.

As you can see in the error message `Message: Invalid domain`, the specified domains are invalid.
The argument `'*.domain, domain'` is neither comma separated nor space separated. It is actually both what is not allowed. Correct would be a comma separated domains like `'*.domain,domain'`.
You can also specify each domain with the repeated `-d` argument and not as a comma seperated arguments.
Example usage:
```commandline
certbot certonly -d '*.domain' -d 'domain'
````
