### ISSUE TITLE
Release that supports certbot 2.x?

### ISSUE THREAD

**Issue by nemchik** [infinityofspace/certbot_dns_porkbun#61]
This is not a bug report.

I notice the master branch has updated dependencies in requirements.txt to support newer versions of certbot. The latest release available is locked at `certbot>=1.18.0,<2.0`

Is there any way a new release that supports certbot 2.x could be pushed?

**Comment by zjp** [comment]
For what it's worth (to the maintainers, I'm not saying anyone else reading this should do what I did) I just took the <2.0 requirement out of the .dist-info/METADATA file's entry on certbot and it worked (using certbot 2.2.0) -- so perhaps a 0.6.1 release to remove that requirement would go smoothly.

**Comment by infinityofspace** [comment]
closed in release [`0.7`](https://github.com/infinityofspace/certbot_dns_porkbun/releases/tag/v0.7)
