### ISSUE TITLE
New API address 

### ISSUE THREAD

**Issue by bfransoo** [infinityofspace/certbot_dns_porkbun#88]
### Problem description

Hey, I am not associated with Porkbun, I'm an end user. 
I got this email today:

Hello there,

The reason you are receiving this email is because you have an API key associated with your account. In order to ensure that any apps or tools you may have that utilize our API, we wanted to let you know about some upcoming critical updates.

We know these kinds of changes are annoying but the time has come to separate the processing of incoming API commands from our website. In previous documentation the hostname porkbun.com was used for the API but we have recently updated it to api.porkbun.com and in the near future will start enforcing its use. Please update the hostname for our API to api.porkbun.com as soon as possible.

CRITICAL UPDATE DETAILS

Type: API Hostname Change

Old Value: porkbun.com

New Value: api.porkbun.com

Deadline: 2024-12-01 00:00:00 UTC

Please note that after the deadline, API calls made to the old hostname will no longer be allowed. If you have any questions or concerns please contact support.

Thank you,
The Porkbun Team

### Solution description

If you haven't already, change any instances of the old hostname to the new one. 

### Checklist

- [X] I have checked for [existing Github issues](https://github.com/infinityofspace/certbot_dns_porkbun/labels/enhancement) and there are no issues for the same feature request.

**Comment by sdrothrock** [comment]
The API address is actually specified by another package used here, [pkb_client](https://github.com/infinityofspace/pkb_client). I've raised [a PR there](https://github.com/infinityofspace/pkb_client/pull/39) for the new address.

**Comment by MrPetovan** [comment]
@sdrothrock Thanks, now that your PR has been merged, what needs to happen here?

**Comment by sdrothrock** [comment]
@MrPetovan As far as I can tell (I'm not involved in either project), @infinityofspace will have to do three things next:

1. Release a new version of `pkb_client`
2. Update `requirements.txt` here in `certbot_dns_porkbun`
3. Release a new version of `certbot_dns_porkbun`

Following that, any other packages or software that are using either `pkb_client` or `certbot_dns_porkbun` will need to update their own dependencies, and so forth.

**Comment by infinityofspace** [comment]
FYI: I will release a new version of the plugin before the deadline of the API domain renaming. Since the API client `pkb_client` contains a major update `v2.0.0` with many breaking changes from version `1.x` to `2.x`, further changes to the plugin will be necessary first after the release of the `v2.0.0` version of the `pkb_client` package. The new `certbot_dns_porkbun` release will also be combined with/support the new `certbot` version `3.x`, which is still pending.

**Comment by MrPetovan** [comment]
Thank you for the update and for your work!
